PACKAGE_NAME="nvfancontrol"
PACKAGE_VERSION="0.2.0"
BUILT_MODULE_NAME[0]="nvfancontrol"
DEST_MODULE_LOCATION[0]="/updates/dkms"
MAKE[0]="'make' KDIR=/lib/modules/${kernelver}/build"
CLEAN="make KDIR=/lib/modules/${kernelver}/build clean"
AUTOINSTALL="yes"
